#!/usr/bin/env python3
"""Export the cross-engine golden vector.

Python is the reference engine; the Rust port must agree with it. Bit-parity is
impossible for anything stochastic (Mersenne Twister vs ChaCha8), so the golden
vector uses a fixed-hit cell at humanize=0, swing=0, vary=0, no fill — the
configuration with the least randomness in it.

It is NOT zero randomness, and that surprised us: `humanize_velocity` floors
`scaled_variance` at 3 (humanizer.py:143), so every hit still draws
`randint(center-3, center+3)` even at humanize=0. Ticks, instruments, event
order and MIDI note numbers are therefore fully deterministic and pinned
exactly; velocities can differ between the engines by at most 6 (±3 each way)
and the Rust test allows exactly that much drift and no more.

Writes plugin/fixtures/golden_vector.json. Regenerate (and re-verify BOTH test
suites) only when the reference engine's output is intentionally changed:

    python export_golden.py
"""

import json
import os

from assembler import assemble

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "plugin", "fixtures", "golden_vector.json")
KIT = os.path.join(HERE, "kit_mappings", "ugritone.json")

# A fixed-hit 4/4 cell with four instruments including ghost snares — enough
# vocabulary that a divergence in velocity levels or bar math shows up.
PARAMS = {
    "cell_name": "raein_melodic_drive",
    "bars": 2,
    "tempo": 120,
    "time_sig": "4/4",
    "humanize": 0.0,
    "swing": 0.0,
    "fill_every": 0,
    "seed": 0,
    "vary": 0.0,
}


def build():
    kit = json.load(open(KIT))["mapping"]
    res = assemble(**PARAMS)
    events = [[tick, kit[inst], vel, inst] for tick, inst, vel in res["events"]]
    return {
        "_comment": "Generated by export_golden.py — do not hand-edit.",
        "params": PARAMS,
        "time_signatures": res["time_signatures"],
        "events": events,
    }


if __name__ == "__main__":
    data = build()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    print(f"Wrote {OUT} ({len(data['events'])} events)")
