use std::collections::HashMap;
use serde::Deserialize;
use rand::Rng;
use rand_chacha::ChaCha8Rng;

use super::cell::{Cell, CellType, Hit, GridEntry, Instrument, Limb, TrigCond, VelocityLevel};

/// Raw JSON format for cell deserialization.
#[derive(Deserialize)]
struct RawCell {
    name: String,
    tags: Vec<String>,
    time_sig: Vec<i32>,
    num_bars: i32,
    humanize: f64,
    role: String,
    #[serde(rename = "type")]
    cell_type: String,
    #[serde(default)]
    hits: Vec<Vec<serde_json::Value>>,
    #[serde(default)]
    grid: Vec<Vec<serde_json::Value>>,
    #[serde(default)]
    limbs: Vec<RawLimb>,
}

/// Raw JSON format for a Euclidean limb.
#[derive(Deserialize)]
struct RawLimb {
    instrument: String,
    pulses: i32,
    steps: i32,
    #[serde(default)]
    rotation: i32,
    #[serde(default = "default_velocity")]
    velocity: String,
    #[serde(default = "default_true")]
    dice_rotate: bool,
}

fn default_velocity() -> String {
    "normal".to_string()
}

fn default_true() -> bool {
    true
}

/// Raw JSON format for the entire export.
#[derive(Deserialize)]
struct RawExport {
    cells: HashMap<String, RawCell>,
    style_pools: HashMap<String, Vec<String>>,
    section_preferences: HashMap<String, Vec<String>>,
}

/// The cell library loaded from builtin.json.
pub struct CellLibrary {
    cells: HashMap<String, Cell>,
    style_pools: HashMap<String, Vec<String>>,
    section_preferences: HashMap<String, Vec<String>>,
    style_names: Vec<String>,
}

/// Embedded builtin cells JSON (generated by export_cells.py).
const BUILTIN_JSON: &str = include_str!("../../cells/builtin.json");

impl CellLibrary {
    /// Load the built-in cell library from the embedded JSON.
    pub fn new() -> Self {
        Self::from_json(BUILTIN_JSON)
    }

    /// Load from a JSON string (for testing or external files).
    pub fn from_json(json_str: &str) -> Self {
        let raw: RawExport = serde_json::from_str(json_str)
            .expect("Failed to parse cell library JSON");

        let mut cells = HashMap::new();
        for (name, raw_cell) in &raw.cells {
            if let Some(cell) = Self::parse_cell(raw_cell) {
                cells.insert(name.clone(), cell);
            }
        }

        let mut style_names: Vec<String> = raw.style_pools.keys().cloned().collect();
        style_names.sort();

        CellLibrary {
            cells,
            style_pools: raw.style_pools,
            section_preferences: raw.section_preferences,
            style_names,
        }
    }

    fn parse_cell(raw: &RawCell) -> Option<Cell> {
        let time_sig = if raw.time_sig.len() >= 2 {
            (raw.time_sig[0], raw.time_sig[1])
        } else {
            (4, 4)
        };

        let cell_type = if raw.cell_type == "probability" {
            CellType::Probability
        } else if raw.cell_type == "euclidean" {
            CellType::Euclidean
        } else {
            CellType::Fixed
        };

        let hits = if cell_type == CellType::Fixed {
            Self::parse_hits(&raw.hits)
        } else {
            Vec::new()
        };

        let grid = if cell_type == CellType::Probability {
            Self::parse_grid(&raw.grid)
        } else {
            Vec::new()
        };

        let limbs = if cell_type == CellType::Euclidean {
            raw.limbs
                .iter()
                .filter_map(|l| {
                    Some(Limb {
                        instrument: Instrument::from_str(&l.instrument)?,
                        pulses: l.pulses,
                        steps: l.steps.max(1),
                        rotation: l.rotation,
                        velocity_level: VelocityLevel::from_str(&l.velocity),
                        dice_rotate: l.dice_rotate,
                    })
                })
                .collect()
        } else {
            Vec::new()
        };

        Some(Cell {
            name: raw.name.clone(),
            tags: raw.tags.clone(),
            time_sig,
            num_bars: raw.num_bars,
            humanize: raw.humanize,
            role: raw.role.clone(),
            cell_type,
            hits,
            grid,
            limbs,
            humanize_per_bar: None,
        })
    }

    fn parse_hits(raw_hits: &[Vec<serde_json::Value>]) -> Vec<Hit> {
        let mut hits = Vec::new();
        for entry in raw_hits {
            let hit = if entry.len() == 5 {
                // 5-tuple: (bar, beat, sub, instrument, velocity_level)
                let bar = entry[0].as_i64().unwrap_or(1) as i32;
                let beat = entry[1].as_i64().unwrap_or(1) as i32;
                let sub = entry[2].as_f64().unwrap_or(0.0);
                let inst_str = entry[3].as_str().unwrap_or("kick");
                let vel_str = entry[4].as_str().unwrap_or("normal");
                if let Some(instrument) = Instrument::from_str(inst_str) {
                    Some(Hit {
                        bar,
                        beat,
                        sub,
                        instrument,
                        velocity_level: VelocityLevel::from_str(vel_str),
                    })
                } else {
                    None
                }
            } else if entry.len() == 4 {
                // 4-tuple: (beat, sub, instrument, velocity_level) — normalize to bar=1
                let beat = entry[0].as_i64().unwrap_or(1) as i32;
                let sub = entry[1].as_f64().unwrap_or(0.0);
                let inst_str = entry[2].as_str().unwrap_or("kick");
                let vel_str = entry[3].as_str().unwrap_or("normal");
                if let Some(instrument) = Instrument::from_str(inst_str) {
                    Some(Hit {
                        bar: 1,
                        beat,
                        sub,
                        instrument,
                        velocity_level: VelocityLevel::from_str(vel_str),
                    })
                } else {
                    None
                }
            } else {
                None
            };
            if let Some(h) = hit {
                hits.push(h);
            }
        }
        hits
    }

    fn parse_grid(raw_grid: &[Vec<serde_json::Value>]) -> Vec<GridEntry> {
        // Accepted forms (mirrors Python _normalize_grid):
        //   5: (beat, sub, inst, prob, vel)
        //   6: (bar, beat, sub, inst, prob, vel)         — position 2 is a number
        //   6: (beat, sub, inst, prob, vel, cond)        — position 2 is a string
        //   7: (bar, beat, sub, inst, prob, vel, cond)
        let mut grid = Vec::new();
        for entry in raw_grid {
            let single_bar_cond = entry.len() == 6 && entry[2].is_string();
            let (bar, rest): (i32, &[serde_json::Value]) = match entry.len() {
                5 => (1, &entry[..]),
                6 if single_bar_cond => (1, &entry[..]),
                6 | 7 => (entry[0].as_i64().unwrap_or(1) as i32, &entry[1..]),
                _ => continue,
            };
            // rest = (beat, sub, inst, prob, vel[, cond])
            if rest.len() < 5 {
                continue;
            }
            let beat = rest[0].as_i64().unwrap_or(1) as i32;
            let sub = rest[1].as_f64().unwrap_or(0.0);
            let inst_str = rest[2].as_str().unwrap_or("kick");
            let prob = rest[3].as_f64().unwrap_or(0.5);
            let vel_str = rest[4].as_str().unwrap_or("normal");
            let cond = rest
                .get(5)
                .and_then(|v| v.as_str())
                .map(TrigCond::from_str)
                .unwrap_or(TrigCond::Always);
            if let Some(instrument) = Instrument::from_str(inst_str) {
                grid.push(GridEntry {
                    bar,
                    beat,
                    sub,
                    instrument,
                    probability: prob,
                    velocity_level: VelocityLevel::from_str(vel_str),
                    condition: cond,
                });
            }
        }
        grid
    }

    /// Get a cell by name.
    pub fn get_cell(&self, name: &str) -> Option<&Cell> {
        self.cells.get(name)
    }

    /// Get all cells for a style pool.
    pub fn get_pool(&self, style: &str) -> Vec<&Cell> {
        if let Some(names) = self.style_pools.get(style) {
            names.iter()
                .filter_map(|name| self.cells.get(name))
                .collect()
        } else {
            Vec::new()
        }
    }

    /// Get the first cell for a style (backward-compat STYLE_MAP equivalent).
    pub fn get_default_cell(&self, style: &str) -> Option<&Cell> {
        self.get_pool(style).into_iter().next()
    }

    /// All fill-role cells (mirrors Python `get_fill_cells`). Sorted by name so
    /// the RNG tie-break is deterministic (the backing map is a HashMap).
    pub fn get_fill_cells(&self) -> Vec<&Cell> {
        let mut fills: Vec<&Cell> = self.cells.values().filter(|c| c.role == "fill").collect();
        fills.sort_by(|a, b| a.name.cmp(&b.name));
        fills
    }


    /// Get all available style names.
    /// Every cell in the library, pooled or not — fills and transitions live
    /// OUTSIDE style pools by design, so walking the pools misses them.
    /// Iteration order is HashMap order: fine for set-building and counting,
    /// never use it anywhere the RNG is consumed.
    pub fn all_cells(&self) -> impl Iterator<Item = &Cell> {
        self.cells.values()
    }

    pub fn style_names(&self) -> &[String] {
        &self.style_names
    }

    /// Number of styles.
    pub fn num_styles(&self) -> usize {
        self.style_names.len()
    }

    /// Get style name by index (for the style parameter).
    pub fn style_by_index(&self, index: usize) -> Option<&str> {
        self.style_names.get(index).map(|s| s.as_str())
    }

    /// Find the index of a style name.
    pub fn style_index(&self, style: &str) -> Option<usize> {
        self.style_names.iter().position(|s| s == style)
    }

    /// Get section preferences (preferred tags for a section type).
    pub fn section_preferences(&self, section_type: &str) -> &[String] {
        self.section_preferences
            .get(section_type)
            .map(|v| v.as_slice())
            .unwrap_or(&[])
    }

    /// Score a cell against section preferences and pick the best match.
    /// Filters by time signature if provided. Breaks ties using the RNG.
    pub fn get_cell_for_section<'a>(
        &'a self,
        pool: &[&'a Cell],
        section_type: &str,
        requested_time_sig: Option<(i32, i32)>,
        rng: &mut ChaCha8Rng,
        next_section: Option<&str>,
        // `prefer_generative` narrows EQUALLY-SCORING candidates to probability
        // /euclidean cells so the dice keeps re-rolling a section. A tiebreak,
        // never a filter — see the comment in assemble_arrangement.
        prefer_generative: bool,
    ) -> Option<&'a Cell> {
        if section_type == "silence" {
            return None;
        }

        // "fill" sections pick from role=="fill" cells library-wide (fills
        // live outside style pools by design), meter-filtered, preferring
        // fills whose into_<next_section> tag matches what comes next.
        // Mirrors Python get_cell_for_section.
        if section_type == "fill" {
            let mut fills = self.get_fill_cells();
            if let Some(ts) = requested_time_sig {
                let ts_match: Vec<&Cell> =
                    fills.iter().filter(|f| f.time_sig == ts).copied().collect();
                if !ts_match.is_empty() {
                    fills = ts_match;
                }
            }
            if fills.is_empty() {
                return None;
            }
            if let Some(next) = next_section {
                let into_tag = format!("into_{}", next);
                let aimed: Vec<&Cell> = fills
                    .iter()
                    .filter(|f| f.tags.iter().any(|t| t == &into_tag))
                    .copied()
                    .collect();
                if !aimed.is_empty() {
                    fills = aimed;
                }
            }
            if fills.len() > 1 {
                let idx = rng.gen_range(0..fills.len());
                return Some(fills[idx]);
            }
            return Some(fills[0]);
        }

        let prefs = self.section_preferences(section_type);

        // Filter by time sig if requested
        let candidates: Vec<&Cell> = if let Some(ts) = requested_time_sig {
            let filtered: Vec<&Cell> = pool.iter()
                .filter(|c| c.time_sig == ts)
                .copied()
                .collect();
            if filtered.is_empty() {
                pool.to_vec()
            } else {
                filtered
            }
        } else {
            pool.to_vec()
        };

        if candidates.is_empty() {
            return None;
        }

        // Score each cell against the section preferences. Earlier prefs weigh
        // more (first = n points, last = 1) — a flat tag count made the leading
        // preference no stronger than the last one, so "blast" could lose to a
        // cell that merely happened to carry two weak tags.
        if !prefs.is_empty() {
            let n = prefs.len() as i32;
            let scored: Vec<(i32, &Cell)> = candidates
                .iter()
                .map(|&cell| {
                    let mut score: i32 = prefs
                        .iter()
                        .enumerate()
                        .filter(|(_, tag)| cell.has_tag(tag))
                        .map(|(i, _)| n - i as i32)
                        .sum();
                    // Built-in tiebreak (+1). Every cell in the plugin is
                    // built-in (export_cells.py excludes user cells), so this
                    // is constant here — kept so the score matches Python's for
                    // the same input, and so the `best_score > 0` gate below
                    // behaves identically.
                    score += 1;
                    (score, cell)
                })
                .collect();

            let best_score = scored.iter().map(|(s, _)| *s).max().unwrap_or(0);
            if best_score > 0 {
                let mut best: Vec<&Cell> = scored
                    .iter()
                    .filter(|(s, _)| *s == best_score)
                    .map(|(_, c)| *c)
                    .collect();
                if prefer_generative && best.len() > 1 {
                    let gen: Vec<&Cell> = best
                        .iter()
                        .filter(|c| c.is_probability() || c.is_euclidean())
                        .copied()
                        .collect();
                    if !gen.is_empty() {
                        best = gen;
                    }
                }
                if best.len() > 1 {
                    let idx = rng.gen_range(0..best.len());
                    return Some(best[idx]);
                }
                return Some(best[0]);
            }
        }

        // No preferences for this section type: take the first cell in the pool
        // deterministically. Drawing from the RNG here (as this used to) shifted
        // every downstream realization for the same seed, which Python never does.
        Some(candidates[0])
    }

    /// Number of cells loaded.
    pub fn num_cells(&self) -> usize {
        self.cells.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand::SeedableRng;

    #[test]
    fn fill_sections_pick_into_aware_fills() {
        // A "fill" section must return a role=="fill" cell, meter-matched,
        // preferring fills tagged into_<next_section>.
        let lib = CellLibrary::new();
        let pool = lib.get_pool("screamo");
        for seed in 0..8u64 {
            let mut rng = ChaCha8Rng::seed_from_u64(seed);
            let cell = lib
                .get_cell_for_section(&pool, "fill", Some((4, 4)), &mut rng, Some("blast"), true)
                .expect("fill section must resolve");
            assert_eq!(cell.role, "fill");
            assert_eq!(cell.time_sig, (4, 4));
            assert!(
                cell.tags.iter().any(|t| t == "into_blast"),
                "into_blast fills exist, so the aimed set must win (got {})",
                cell.name
            );
        }
        // Odd meter: 7/8 fill exists and is chosen.
        let mut rng = ChaCha8Rng::seed_from_u64(1);
        let cell = lib
            .get_cell_for_section(&pool, "fill", Some((7, 8)), &mut rng, Some("blast"), true)
            .expect("7/8 fill must resolve");
        assert_eq!(cell.time_sig, (7, 8));
        assert_eq!(cell.role, "fill");
    }

    /// The telegraph announces the section name, so the section had better get
    /// the cell it asked for. Regression: generative narrowing ran BEFORE
    /// scoring, so build/blast/breakdown all collapsed onto the style's single
    /// probability grid and the fixed blast cell was unreachable — the plugin
    /// said "BLAST NOW" over the same groove as the verse.
    #[test]
    fn section_intent_outranks_generative_preference() {
        let lib = CellLibrary::new();
        // (style, section, tag the chosen cell must carry)
        let cases = [
            ("screamo", "blast", "blast"),
            ("screamo", "breakdown", "breakdown"),
            ("liturgy", "blast", "blast"),
            ("euro_screamo", "blast", "blast"),
        ];
        for (style, section, want_tag) in cases {
            let pool = lib.get_pool(style);
            for seed in 0..6u64 {
                let mut rng = ChaCha8Rng::seed_from_u64(seed);
                let cell = lib
                    .get_cell_for_section(&pool, section, Some((4, 4)), &mut rng, None, true)
                    .expect("section must resolve");
                assert!(
                    cell.has_tag(want_tag),
                    "{style}/{section} seed {seed}: picked '{}' ({:?}), which is not a {want_tag} cell",
                    cell.name, cell.tags
                );
            }
        }
    }

    #[test]
    fn test_load_builtin() {
        let lib = CellLibrary::new();
        assert!(lib.num_cells() > 0, "Should have loaded some cells");
        assert!(lib.num_styles() > 0, "Should have loaded some styles");
    }

    #[test]
    fn test_get_cell() {
        let lib = CellLibrary::new();
        let cell = lib.get_cell("blast_traditional");
        assert!(cell.is_some(), "blast_traditional should exist");
        let cell = cell.unwrap();
        assert_eq!(cell.time_sig, (4, 4));
        assert!(!cell.hits.is_empty());
    }

    #[test]
    fn test_style_pool() {
        let lib = CellLibrary::new();
        let pool = lib.get_pool("screamo");
        assert!(!pool.is_empty(), "screamo pool should have cells");
    }

    #[test]
    fn test_style_by_index() {
        let lib = CellLibrary::new();
        let name = lib.style_by_index(0);
        assert!(name.is_some());
    }
}
