use std::collections::HashMap;
use serde::Deserialize;
use rand::Rng;
use rand_chacha::ChaCha8Rng;

use super::cell::{Cell, CellType, Hit, GridEntry, Instrument, VelocityLevel};

/// Raw JSON format for cell deserialization.
#[derive(Deserialize)]
struct RawCell {
    name: String,
    tags: Vec<String>,
    time_sig: Vec<i32>,
    num_bars: i32,
    humanize: f64,
    role: String,
    #[serde(rename = "type")]
    cell_type: String,
    #[serde(default)]
    hits: Vec<Vec<serde_json::Value>>,
    #[serde(default)]
    grid: Vec<Vec<serde_json::Value>>,
}

/// Raw JSON format for the entire export.
#[derive(Deserialize)]
struct RawExport {
    cells: HashMap<String, RawCell>,
    style_pools: HashMap<String, Vec<String>>,
    section_preferences: HashMap<String, Vec<String>>,
}

/// The cell library loaded from builtin.json.
pub struct CellLibrary {
    cells: HashMap<String, Cell>,
    style_pools: HashMap<String, Vec<String>>,
    section_preferences: HashMap<String, Vec<String>>,
    style_names: Vec<String>,
}

/// Embedded builtin cells JSON (generated by export_cells.py).
const BUILTIN_JSON: &str = include_str!("../../cells/builtin.json");

impl CellLibrary {
    /// Load the built-in cell library from the embedded JSON.
    pub fn new() -> Self {
        Self::from_json(BUILTIN_JSON)
    }

    /// Load from a JSON string (for testing or external files).
    pub fn from_json(json_str: &str) -> Self {
        let raw: RawExport = serde_json::from_str(json_str)
            .expect("Failed to parse cell library JSON");

        let mut cells = HashMap::new();
        for (name, raw_cell) in &raw.cells {
            if let Some(cell) = Self::parse_cell(raw_cell) {
                cells.insert(name.clone(), cell);
            }
        }

        let mut style_names: Vec<String> = raw.style_pools.keys().cloned().collect();
        style_names.sort();

        CellLibrary {
            cells,
            style_pools: raw.style_pools,
            section_preferences: raw.section_preferences,
            style_names,
        }
    }

    fn parse_cell(raw: &RawCell) -> Option<Cell> {
        let time_sig = if raw.time_sig.len() >= 2 {
            (raw.time_sig[0], raw.time_sig[1])
        } else {
            (4, 4)
        };

        let cell_type = if raw.cell_type == "probability" {
            CellType::Probability
        } else {
            CellType::Fixed
        };

        let hits = if cell_type == CellType::Fixed {
            Self::parse_hits(&raw.hits)
        } else {
            Vec::new()
        };

        let grid = if cell_type == CellType::Probability {
            Self::parse_grid(&raw.grid)
        } else {
            Vec::new()
        };

        Some(Cell {
            name: raw.name.clone(),
            tags: raw.tags.clone(),
            time_sig,
            num_bars: raw.num_bars,
            humanize: raw.humanize,
            role: raw.role.clone(),
            cell_type,
            hits,
            grid,
            humanize_per_bar: None,
        })
    }

    fn parse_hits(raw_hits: &[Vec<serde_json::Value>]) -> Vec<Hit> {
        let mut hits = Vec::new();
        for entry in raw_hits {
            let hit = if entry.len() == 5 {
                // 5-tuple: (bar, beat, sub, instrument, velocity_level)
                let bar = entry[0].as_i64().unwrap_or(1) as i32;
                let beat = entry[1].as_i64().unwrap_or(1) as i32;
                let sub = entry[2].as_f64().unwrap_or(0.0);
                let inst_str = entry[3].as_str().unwrap_or("kick");
                let vel_str = entry[4].as_str().unwrap_or("normal");
                if let Some(instrument) = Instrument::from_str(inst_str) {
                    Some(Hit {
                        bar,
                        beat,
                        sub,
                        instrument,
                        velocity_level: VelocityLevel::from_str(vel_str),
                    })
                } else {
                    None
                }
            } else if entry.len() == 4 {
                // 4-tuple: (beat, sub, instrument, velocity_level) — normalize to bar=1
                let beat = entry[0].as_i64().unwrap_or(1) as i32;
                let sub = entry[1].as_f64().unwrap_or(0.0);
                let inst_str = entry[2].as_str().unwrap_or("kick");
                let vel_str = entry[3].as_str().unwrap_or("normal");
                if let Some(instrument) = Instrument::from_str(inst_str) {
                    Some(Hit {
                        bar: 1,
                        beat,
                        sub,
                        instrument,
                        velocity_level: VelocityLevel::from_str(vel_str),
                    })
                } else {
                    None
                }
            } else {
                None
            };
            if let Some(h) = hit {
                hits.push(h);
            }
        }
        hits
    }

    fn parse_grid(raw_grid: &[Vec<serde_json::Value>]) -> Vec<GridEntry> {
        let mut grid = Vec::new();
        for entry in raw_grid {
            let ge = if entry.len() == 6 {
                // 6-tuple: (bar, beat, sub, instrument, probability, velocity_level)
                let bar = entry[0].as_i64().unwrap_or(1) as i32;
                let beat = entry[1].as_i64().unwrap_or(1) as i32;
                let sub = entry[2].as_f64().unwrap_or(0.0);
                let inst_str = entry[3].as_str().unwrap_or("kick");
                let prob = entry[4].as_f64().unwrap_or(0.5);
                let vel_str = entry[5].as_str().unwrap_or("normal");
                if let Some(instrument) = Instrument::from_str(inst_str) {
                    Some(GridEntry {
                        bar,
                        beat,
                        sub,
                        instrument,
                        probability: prob,
                        velocity_level: VelocityLevel::from_str(vel_str),
                    })
                } else {
                    None
                }
            } else if entry.len() == 5 {
                // 5-tuple: (beat, sub, instrument, probability, velocity_level) — bar=1
                let beat = entry[0].as_i64().unwrap_or(1) as i32;
                let sub = entry[1].as_f64().unwrap_or(0.0);
                let inst_str = entry[2].as_str().unwrap_or("kick");
                let prob = entry[3].as_f64().unwrap_or(0.5);
                let vel_str = entry[4].as_str().unwrap_or("normal");
                if let Some(instrument) = Instrument::from_str(inst_str) {
                    Some(GridEntry {
                        bar: 1,
                        beat,
                        sub,
                        instrument,
                        probability: prob,
                        velocity_level: VelocityLevel::from_str(vel_str),
                    })
                } else {
                    None
                }
            } else {
                None
            };
            if let Some(g) = ge {
                grid.push(g);
            }
        }
        grid
    }

    /// Get a cell by name.
    pub fn get_cell(&self, name: &str) -> Option<&Cell> {
        self.cells.get(name)
    }

    /// Get all cells for a style pool.
    pub fn get_pool(&self, style: &str) -> Vec<&Cell> {
        if let Some(names) = self.style_pools.get(style) {
            names.iter()
                .filter_map(|name| self.cells.get(name))
                .collect()
        } else {
            Vec::new()
        }
    }

    /// Get the first cell for a style (backward-compat STYLE_MAP equivalent).
    pub fn get_default_cell(&self, style: &str) -> Option<&Cell> {
        self.get_pool(style).into_iter().next()
    }

    /// Get all available style names.
    pub fn style_names(&self) -> &[String] {
        &self.style_names
    }

    /// Number of styles.
    pub fn num_styles(&self) -> usize {
        self.style_names.len()
    }

    /// Get style name by index (for the style parameter).
    pub fn style_by_index(&self, index: usize) -> Option<&str> {
        self.style_names.get(index).map(|s| s.as_str())
    }

    /// Find the index of a style name.
    pub fn style_index(&self, style: &str) -> Option<usize> {
        self.style_names.iter().position(|s| s == style)
    }

    /// Get section preferences (preferred tags for a section type).
    pub fn section_preferences(&self, section_type: &str) -> &[String] {
        self.section_preferences
            .get(section_type)
            .map(|v| v.as_slice())
            .unwrap_or(&[])
    }

    /// Score a cell against section preferences and pick the best match.
    /// Filters by time signature if provided. Breaks ties using the RNG.
    pub fn get_cell_for_section<'a>(
        &self,
        pool: &[&'a Cell],
        section_type: &str,
        requested_time_sig: Option<(i32, i32)>,
        rng: &mut ChaCha8Rng,
    ) -> Option<&'a Cell> {
        if section_type == "silence" {
            return None;
        }

        let prefs = self.section_preferences(section_type);

        // Filter by time sig if requested
        let candidates: Vec<&Cell> = if let Some(ts) = requested_time_sig {
            let filtered: Vec<&Cell> = pool.iter()
                .filter(|c| c.time_sig == ts)
                .copied()
                .collect();
            if filtered.is_empty() {
                pool.to_vec()
            } else {
                filtered
            }
        } else {
            pool.to_vec()
        };

        if candidates.is_empty() {
            return None;
        }

        // Score each cell by counting matching tags
        let scored: Vec<(i32, &Cell)> = candidates.iter()
            .map(|&cell| {
                let score = prefs.iter()
                    .filter(|tag| cell.has_tag(tag))
                    .count() as i32;
                (score, cell)
            })
            .collect();

        let best_score = scored.iter().map(|(s, _)| *s).max().unwrap_or(0);
        let best: Vec<&Cell> = scored.iter()
            .filter(|(s, _)| *s == best_score)
            .map(|(_, c)| *c)
            .collect();

        if best.len() == 1 {
            Some(best[0])
        } else {
            let idx = rng.gen_range(0..best.len());
            Some(best[idx])
        }
    }

    /// Number of cells loaded.
    pub fn num_cells(&self) -> usize {
        self.cells.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_load_builtin() {
        let lib = CellLibrary::new();
        assert!(lib.num_cells() > 0, "Should have loaded some cells");
        assert!(lib.num_styles() > 0, "Should have loaded some styles");
    }

    #[test]
    fn test_get_cell() {
        let lib = CellLibrary::new();
        let cell = lib.get_cell("blast_traditional");
        assert!(cell.is_some(), "blast_traditional should exist");
        let cell = cell.unwrap();
        assert_eq!(cell.time_sig, (4, 4));
        assert!(!cell.hits.is_empty());
    }

    #[test]
    fn test_style_pool() {
        let lib = CellLibrary::new();
        let pool = lib.get_pool("screamo");
        assert!(!pool.is_empty(), "screamo pool should have cells");
    }

    #[test]
    fn test_style_by_index() {
        let lib = CellLibrary::new();
        let name = lib.style_by_index(0);
        assert!(name.is_some());
    }
}
